import requests
import json
if __name__ == '__main__':

    categories = [
        {"name": "Vino"},
        {"name": "Deporte"},
        {"name": "Coche"},
        {"name": "Moto"},
        {"name": "Paseo"},
        {"name": "Senderismo"},
        {"name": "Ciclismo"},
        {"name": "Pesca"},
        {"name": "Caza"},
        {"name": "Aventura"},
        {"name": "Agroturismo"},
        {"name": "Equitación"},
        {"name": "Observación de aves"},
        {"name": "Camping"},
        {"name": "Escalada"},
        {"name": "Navegación"},
        {"name": "Fotografía rural"},
        {"name": "Relax"},
        {"name": "Trekking"},
        {"name": "Gastronomía local"},
        {"name": "Recolección de setas"},
        {"name": "Arte y cultura local"},
        {"name": "Vía ferrata"},
        {"name": "Rutas en 4x4"},
        {"name": "Turismo rural"},
        {"name": "Caballos"},
        {"name": "Conducción en la naturaleza"},
        {"name": "Talleres artesanales"},
        {"name": "Rutas gastronómicas"},
        {"name": "Termalismo"},
        {"name": "Relax en la naturaleza"},
        {"name": "Degustación de vinos"},
        {"name": "Cata de aceites"},
        {"name": "Talleres de cocina tradicional"},
        {"name": "Mercados locales"},
        {"name": "Fiestas populares"},
        {"name": "Rutas de queso"},
        {"name": "Recogida de frutas"},
        {"name": "Catas de productos locales"},
        {"name": "Visitas a bodegas"},
        {"name": "Rutas de miel"},
        {"name": "Jornadas de caza y pesca"},
        {"name": "Festivales rurales"},
        {"name": "Senderismo en la naturaleza"},
        {"name": "Visita a granjas"},
        {"name": "Arte rural"},
        {"name": "Días de campo"},
        {"name": "Excursiones en tractor"},
        {"name": "Rutas en quad"},
        {"name": "Paseos en carro"},
        {"name": "Actividades en granja"},
        {"name": "Fiestas de la cosecha"},
        {"name": "Escapadas rurales"},
        {"name": "Rutas en bici de montaña"},
        {"name": "Convivencia con animales de granja"},
        {"name": "Rutas por los campos"},
        {"name": "Observación de estrellas"},
        {"name": "Fiestas de tradiciones locales"},
        {"name": "Jornadas de intercambio cultural"},
        {"name": "Ruta de los embutidos"},
        {"name": "Catas de cerveza artesanal"},
        {"name": "Talleres de cerámica"},
        {"name": "Recreación histórica"},
        {"name": "Rutas por caminos rurales"},
        {"name": "Vuelta en carreta tirada por caballos"},
        {"name": "Visitas a museos rurales"},
        {"name": "Talleres de cestería"},
        {"name": "Escuelas de oficios tradicionales"},
        {"name": "Rutas de pastores"},
        {"name": "Rutas por viñedos"},
        {"name": "Caminos del vino"},
        {"name": "Convivencia en aldeas"}
    ]

    for category in categories:
        try:
            response = requests.post(url='http://localhost:8000/categories/create_category/',  data=json.dumps(category))
            print(response.status_code)
        except requests.exceptions.RequestException as e:
            print(f"Error en la solicitud: {e}")

