[client]
showErrorDetails = false
showSidebarNavigation = false

[theme]

base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#82b29a"

# Background color for the main content area.
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#323232"

# Color used for almost all text.
textColor = "#F3E8EB"

